#!/bin/bash

function append_var_if_defined
{
    VAR_NAME=$1
    OUTPUT=$2
    grep -qE "^${VAR_NAME}=" ${OUTPUT}||env|grep -E "^${VAR_NAME}=">>${OUTPUT}
}
VAR_LIST="RAILS_DB_HOST RAILS_DB_PORT RAILS_DB_USER RAILS_DB_PASSWORD RAILS_DB_NAME MAIL_HOST MAIL_ASSETS_URL_BASE MAIL_FROM SMTP_HOST SECRET_BASE SIDEKIQ_REDIS_URL CODIFLIGNE_API_URL REDIS_CACHE_STORE_URL RAILS_LOG_TO_STDOUT PATH"

TMPF=$(tempfile)
for v in $VAR_LIST; do
    append_var_if_defined $v $TMPF   
done

crontab -l >> $TMPF
cat $TMPF |crontab -
rm $TMPF

exec cron -f
